### PR TITLE
adding ability to define redirects with regex

### PR DESCRIPTION
**Pull request by biw**
> Fixes #92
>
> I have implemented an example repo that is using this fork of the buildpack and it is working exactly as expected.
>
> You can see a (silly) index page that explains what is going on here: static-test-mansona.herokuapp.com
>
> Essentially what it allows you to do is to define indvidual rules as regex as you see fit, this way you can make full use of wildcards and domain redirects. Here is an example config:
>
> ```
> {
>  "root": "public_html",
>  "clean_urls": true,
>  "redirects": {
>    "/standard/": {
>      "url": "https://heroku.com",
>      "status": 302
>    },
>    "/magic(.*)": {
>      "url": "https://stonecircle.io$1",
>      "regex": true
>    }
>  }
> } 
> ```
>
> As you can see that if you visit static-test-mansona.herokuapp.com/magic/opensource it will redirect you to stonecircle.io/opensource 👍

 -- @mansona

See https://github.com/heroku/heroku-buildpack-static/pull/105/files

### CODE REVIEW

**Comment by EloB** [comment]
Have you tried to merge this with the official library?

**Comment by EloB** [comment]
A nice improvement should be to `location ~ "<%= path %>"`. One problem with current implementation was that `\d{14}` or quantifier didn't work.

**Comment by biw** [comment]
@EloB they don't seem to be actively maintaining the repo, that's why I moved it over to here. However, due to Heroku not actively maintaining many of their repos, I decided to move all projects away from them. Hope you have better luck than me 😄

**Comment by EloB** [comment]
Thanks for the info :)

**Pull request merged**
